version: "3.8"

services:
  django:
    build: .
    command: gunicorn feedback_analyzer.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    networks:
      - app_network  

  mongo:
    build: db
    container_name: mongo_db

    expose:
      - "27017"  
    volumes:
      - mongo_data:/data/db
      - ./db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
    networks:
      - app_network 

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./web-server/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django
    networks:
      - app_network  

volumes:
  mongo_data:

networks:
  app_network: 
    driver: bridge
