version: "3.8"

services:
  django:
    build: .
    command: gunicorn feedback_analyzer.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    build: db
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./db/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh  

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./web-server/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - django

volumes:
  mongo_data:
